/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Checkbox: typeof import('../packages/components/components/checkbox/index.vue')['default']
    Date: typeof import('../packages/components/components/date/index.vue')['default']
    MyDetail: typeof import('../packages/components/Detail/index.vue')['default']
    MyDialog: typeof import('../packages/components/Dialog/index.vue')['default']
    MyEdit: typeof import('../packages/components/Edit/index.vue')['default']
    MyForm: typeof import('../packages/components/Form/index.vue')['default']
    Input: typeof import('../packages/components/components/input/index.vue')['default']
    Item: typeof import('../packages/components/components/form/item.vue')['default']
    Pagination: typeof import('../packages/components/components/Pagination/index.vue')['default']
    Radio: typeof import('../packages/components/components/radio/index.vue')['default']
    RightToolbar: typeof import('../packages/components/components/RightToolbar/index.vue')['default']
    Select: typeof import('../packages/components/components/select/index.vue')['default']
    Switch: typeof import('../packages/components/components/switch/index.vue')['default']
    MyTable: typeof import('../packages/components/Table/index.vue')['default']
    TableV2: typeof import('../packages/components/TableV2/index.vue')['default']
  }
}
