/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Checkbox: typeof import('./components/components/checkbox/index.vue')['default']
    Date: typeof import('./components/components/date/index.vue')['default']
    Detail: typeof import('./components/Detail/index.vue')['default']
    Dialog: typeof import('./components/Dialog/index.vue')['default']
    Edit: typeof import('./components/Edit/index.vue')['default']
    Form: typeof import('./components/Form/index.vue')['default']
    Input: typeof import('./components/components/input/index.vue')['default']
    Item: typeof import('./components/components/form/item.vue')['default']
    Pagination: typeof import('./components/components/Pagination/index.vue')['default']
    Radio: typeof import('./components/components/radio/index.vue')['default']
    RightToolbar: typeof import('./components/components/RightToolbar/index.vue')['default']
    Select: typeof import('./components/components/select/index.vue')['default']
    Switch: typeof import('./components/components/switch/index.vue')['default']
    Table: typeof import('./components/Table/index.vue')['default']
    TableV2: typeof import('./components/TableV2/index.vue')['default']
  }
}
